#!/bin/bash
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

rm -rf "${HOME}/.vimrc" && ln -s "${DIR}/home/.vimrc" "${HOME}/.vimrc"
rm -rf "${HOME}/.vim" && ln -s "${DIR}/home/.vim" "${HOME}/.vim"
