#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

rm "${HOME}/.vimrc" && ln -s "${DIR}/home/.vimrc" "${HOME}/.vimrc"
rm "${HOME}/.vimrc-commit" && ln -s "${DIR}/home/.vimrc-commit" "${HOME}/.vimrc-commit"
rm "${HOME}/.vim" && ln -s "${DIR}/home/.vim" "${HOME}/.vim"
