#!/bin/bash
#
# update functionlists for 
# - PHP

DONE_SOMETHING=0

cd ~/.vim

#
# PHP
#
wget -O /tmp/php-functionlist.txt "http://svn.php.net/viewvc/phpdoc/doc-base/trunk/funclist.txt?view=co"
diff -q /tmp/php-functionlist.txt ~/.vim/assorted_scripts/php-functionlist.txt 2>&1 > /dev/null
if [[ "$?" -eq "1" ]]; then
  mv /tmp/php-functionlist.txt ~/.vim/assorted_scripts/
  DONE_SOMETHING=1
else
  rm /tmp/php-functionlist.txt
fi


if [[ $DONE_SOMETHING == 1 ]]; then
  git add home/.vim/assorted_scripts/php-functionlist.txt
  git ci -m "update ominicomplete functionlists as of `date`"
fi
