#!/bin/bash
#
# Updates all included submodules to the recent COMMIT
# See http://stackoverflow.com/questions/1030169/git-easy-way-pull-latest-of-all-submodules
# and ... http://woss.name/2008/04/09/using-git-submodules-to-track-plugins/
#
# Short version:
# Unlike svn:externals "git submodule" adds a submodule AT A SPECIFIC commit. There's no auto-update!
#

build_tern() {
  echo "Building TERN via npm install"
  cd home/.vim/bundle/tern_for_vim/
  npm update
  npm install --force
  cd ../../../..
}

# First update all submodules to HEAD
git submodule foreach git pull origin master

# Build tern
build_tern

# build vimproc
cd home/.vim/bundle/vimproc
make
cd ../../../

# Commit
git add home/.vim/bundle/*
git commit -am "Updated submodules to the newest version as of `date`" 


echo
echo "Changes in Submodules ..."
echo "-------------------------"
echo
CHANGES=$(git log -1 -p --oneline | grep "+++" | sed "s/^.*bundle\///")
echo $CHANGES
echo

